# Generated by Django 4.2 on 2023-04-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GENQModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=250)),
                ('l_name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('country', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
                ('zip', models.IntegerField()),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
