# Generated by Django 4.2 on 2023-04-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GENQapp', '0002_alter_genqmodels_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genqmodels',
            name='date',
            field=models.DateField(verbose_name='mm/dd/yy'),
        ),
    ]
