# Generated by Django 4.1.7 on 2023-05-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GENQapp', '0004_alter_genqmodels_date_alter_genqmodels_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genqmodels',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='genqmodels',
            name='phone1',
            field=models.IntegerField(default=256),
        ),
        migrations.AlterField(
            model_name='genqmodels',
            name='phone2',
            field=models.IntegerField(default=256),
        ),
    ]
